#pragma once
#include <Arduino.h>
namespace solarpilot::web {
inline constexpr char kPage[] PROGMEM = R"HTML(<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SolarPilot · Übersicht</title>
<style>
:root{font-family:system-ui,sans-serif;color:#17332b;background:#eef3ef}*{box-sizing:border-box}body{max-width:1080px;margin:auto;padding:24px}nav{display:flex;gap:18px;align-items:center;margin-bottom:30px}nav strong{font-size:24px;margin-right:auto}a{color:#13674b}h1{font-size:32px;margin:0 0 8px}h2{font-size:20px}p{line-height:1.6;color:#4d625a}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{background:white;padding:22px;border-radius:16px;border:1px solid #dae5dd;margin-top:16px}.value{font-size:30px;font-weight:700;margin:12px 0}.hint{font-size:14px;color:#596c63}.badge{padding:8px 12px;background:#e0eee5;border-radius:8px;display:inline-block}button{border:0;border-radius:9px;background:#176346;color:white;padding:12px 16px;cursor:pointer;font:inherit;margin:4px 6px 4px 0}button.secondary{background:#e8eeea;color:#17332b}button:disabled{opacity:.5}input{font:inherit;padding:10px;max-width:100%}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#10291f;color:#d5f1e1;padding:16px;border-radius:10px;max-height:440px;overflow:auto;font-size:13px}details{margin-top:16px}dt{font-weight:bold;margin-top:12px}dd{margin-left:0;color:#52675b}.danger{color:#90321e}[hidden]{display:none!important}#connection{margin:16px 0}footer{padding:24px 0;color:#61746a}form{margin:16px 0}#result{white-space:pre-wrap}
</style></head><body>
<nav><strong>☀ SolarPilot</strong><a href="/">Übersicht</a><a href="/admin">Administration</a></nav>
<h1>Dein Solarstrom im Blick</h1><p>SolarPilot nutzt überschüssigen Solarstrom und überwacht die Verbindung zu deinen Geräten.</p>
<div id="connection" class="badge" role="status">Verbindung wird hergestellt …</div>
<div class="grid"><section class="card"><h2>Stromfluss am Haus</h2><div id="power" class="value">—</div><div id="direction">Warte auf Messwerte</div><p class="hint" id="age">Ein alter Messwert ist keine aktuelle Messung.</p></section>
<section class="card"><h2>Steckdose</h2><div id="output" class="value">—</div><p id="outputHint" class="hint">Der Zustand wird erst nach erfolgreicher Geräteantwort übernommen.</p></section>
<section class="card"><h2>WLAN-Verbindung</h2><div id="signal" class="value">—</div><p id="signalHint" class="hint"></p></section></div>
<section class="card"><h2>Was passiert gerade?</h2><p id="summary">Status wird geladen …</p><p id="test" class="danger"></p><details><summary>Technische Einzelheiten verständlich erklärt</summary><dl><dt>Wechselrichter</dt><dd id="inverter"></dd><dt>Erneute Leseversuche</dt><dd id="retries"></dd><dt>Ausgebliebene Antworten</dt><dd id="timeouts"></dd><dt>Netzwerkprüfung</dt><dd id="probe"></dd><dt>Sicherheitsabschaltung</dt><dd>Ohne gültige Wechselrichterdaten fordert SolarPilot nach 30 Sekunden AUS an. Bei Verbindungsproblemen wird AUS weiter versucht, bis das Gerät antwortet.</dd></dl></details></section>
<div id="admin" hidden><section class="card"><h2>Live-Protokoll</h2><p>Dieselben SolarPilot-Meldungen wie am USB-Monitor: Messwerte, Schaltvorgänge und Verbindungsversuche. Gespeichert werden die letzten 64 Meldungen im Arbeitsspeicher. Nach einem Neustart beginnt das Protokoll neu. Während eines WLAN-Ausfalls ist keine Liveanzeige möglich.</p><button class="secondary" id="pause">Anzeige pausieren</button><span id="logState" role="status"></span><pre id="logs" aria-label="Live-Protokoll">Warte auf Meldungen …</pre></section>
<section class="card"><h2>Wartung und Diagnose</h2><p>Tests können die Steckdose schalten. Nur ohne angeschlossenen Verbraucher testen. Webtests enden spätestens nach zwei Minuten; „Tests beenden“ schaltet die Steckdose vorher bestätigt aus.</p>
<button data-command="diagnose" class="secondary">Verbindung prüfen</button><button data-command="cycle">Ein/Aus-Test starten</button><button data-command="goodwe-loss">Sicherheitsabschaltung testen</button><button data-command="wifi-loss">WLAN-Unterbrechung testen (40 Sekunden)</button><button data-command="switch-failure">Schaltfehler testen</button><button data-command="stop" class="secondary">Alle Tests beenden</button><button data-command="restart" class="secondary">SolarPilot neu starten</button><p id="result" role="status"></p></section>
<section class="card"><h2>Software über WLAN aktualisieren</h2><p>Wähle die für diesen ESP32-C3 gebaute Datei <b>firmware.bin</b>. SolarPilot fordert zuerst AUS an und prüft die Geräteantwort. Ohne bestätigtes AUS wird das Update abgelehnt. Während der Übertragung pausiert die Regelung; danach startet das Gerät neu.</p><p>Die Stromversorgung während des Updates nicht trennen. Bei ausgefallenem WLAN oder nicht startender Software kann USB weiterhin nötig sein.</p><form id="upload"><input type="file" id="firmware" accept=".bin" required><button>Software installieren</button></form><p id="uploadResult" role="status"></p></section></div>
<section class="card" id="loginHint"><h2>Administration</h2><p>Live-Protokoll, Tests und Updates sind durch eine Anmeldung geschützt.</p><a href="/admin">Als Administrator anmelden</a></section>
<footer>Lokaler Betrieb · Keine Cloud erforderlich · Der Adminzugang ist nur für dein vertrauenswürdiges Heimnetz gedacht.</footer>
<script>
const admin=location.pathname==='/admin'||location.pathname==='/update';let token='',paused=false;const $=id=>document.getElementById(id);$('admin').hidden=!admin;$('loginHint').hidden=admin;
async function getJson(url){const r=await fetch(url,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error('Verbindung oder Anmeldung fehlgeschlagen');return r.json()}
async function status(){try{const s=await getJson('/api/status');$('connection').textContent='Verbunden · '+s.health;$('power').textContent=s.valid?Math.abs(s.power).toFixed(0)+' W':'—';$('direction').textContent=!s.valid?'Kein aktueller Messwert':s.power>0?'Einspeisung ins Stromnetz':s.power<0?'Bezug aus dem Stromnetz':'Ausgeglichener Stromfluss';$('age').textContent=s.age===null?'Noch keine Messung':'Letzte Messung vor '+Math.floor(s.age/1000)+' Sekunden';$('output').textContent=s.on?'Eingeschaltet':'Ausgeschaltet';$('outputHint').textContent=s.pending?'AUS noch nicht bestätigt – weitere Versuche laufen.':s.retry?'Gerätebefehl noch nicht bestätigt – erneuter Versuch folgt.':s.real?'Shelly-Steckdose · zuletzt bestätigter Zustand':'Simulation – kein reales Gerät wird geschaltet';$('signal').textContent=s.rssi===null?'Getrennt':s.rssi+' dBm';$('signalHint').textContent=s.rssi===null?'Keine WLAN-Verbindung':s.rssi>=-60?'Guter Empfang':s.rssi>=-75?'Mittlerer Empfang':'Schwacher Empfang – Verbindungsprobleme sind möglich';$('summary').textContent=s.health==='In Ordnung'?'SolarPilot verarbeitet Messwerte und steuert die Steckdose automatisch.':'SolarPilot versucht Verbindungen wiederherzustellen. Sicherheitsabschaltungen haben Vorrang.';$('inverter').textContent=s.goodwe?'GoodWe-Verbindung vorbereitet; die Aktualität siehst du beim Messwert.':'GoodWe ist momentan nicht verbunden.';$('retries').textContent=s.retries+' zusätzliche Versuche seit dem Start.';$('timeouts').textContent=s.timeouts+' Abfragen ohne rechtzeitige Antwort seit dem Start.';$('probe').textContent=s.probes+' Prüfungen. Ein geschlossener TCP-Port 80 am Router allein bedeutet nicht, dass das WLAN ausgefallen ist.';$('test').textContent=s.test?'TESTBETRIEB AKTIV – Werte oder Fehler werden simuliert.':''}catch(e){$('connection').textContent='Keine Verbindung – angezeigte Werte können veraltet sein';$('power').textContent='—';$('direction').textContent='Aktuelle Messung nicht erreichbar';$('summary').textContent='Die Browseransicht wartet auf SolarPilot.'}}
async function logs(){if(!admin||paused)return;try{const s=await getJson('/api/logs');token=s.token;$('logs').textContent=s.entries.map(e=>'['+(e.ms/1000).toFixed(1)+' s seit Start] '+e.text).join('\n');$('logs').scrollTop=$('logs').scrollHeight;$('logState').textContent='Live · Aktualisierung alle 2 Sekunden'}catch(e){$('logState').textContent='Verbindung unterbrochen – letzte Meldungen bleiben sichtbar'}}
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Anzeige fortsetzen':'Anzeige pausieren';$('logState').textContent=paused?'Pausiert':'';if(!paused)logs()};
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=async()=>{if(!token){$('result').textContent='Bitte warten, bis das Live-Protokoll verbunden ist.';return}if(b.dataset.command!=='diagnose'&&!confirm(b.textContent+'? Tests können die Steckdose schalten.'))return;b.disabled=true;try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({command:b.dataset.command,token})});$('result').textContent=await r.text()}catch(e){$('result').textContent='Keine Antwort. Bitte Live-Protokoll und Verbindungsstatus prüfen.'}finally{b.disabled=false}});
$('upload').onsubmit=async e=>{e.preventDefault();if(!token){$('uploadResult').textContent='Bitte auf die Verbindung warten.';return}if(!confirm('Software installieren? Die Steckdose wird ausgeschaltet und SolarPilot startet nach dem Update neu.'))return;const f=$('firmware').files[0];if(!f||!f.name.endsWith('.bin'))return;const data=new FormData();data.append('firmware',f);$('uploadResult').textContent='Übertragung läuft – Stromversorgung nicht trennen.';try{const r=await fetch('/update?token='+encodeURIComponent(token),{method:'POST',body:data});$('uploadResult').textContent=await r.text()}catch(e){$('uploadResult').textContent='Verbindung unterbrochen. Bitte nach dem Neustart den Status prüfen.'}};
status();logs();setInterval(status,5000);setInterval(logs,2000);
</script></body></html>)HTML";
}
